spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 398457174795-5smar0ij8pb8elvq4t3emurehj0aljki.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          kakao:
            client-id: cb13f4fee8cbecb025ee389e86621291
            client-secret: 05Ri0SPNbDkld59eMhpLDOlTG6gt25xE
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
            - profile_nickname
            - account_email
            
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          